### ISSUE TITLE
Question about the Hopfield network for TSP problem

### ISSUE THREAD

**Issue by JackyXiao1515** [DenseLance/hopfield-networks#1]
Hi! I'm really appreciate for your code and it helps me so much to understanding the paper. I have a question about the initial state of the u_xi matrix, as your code in follow:

        # (i) All initial output potentials were set
        self.input_potential = np.zeros(self.input_potential_shape) # refers to variable u
        self.output_potential = self.output_potential_function(self.input_potential) # refers to variable v
        if strategy == "A":
            self.output_potential = np.random.uniform(0, 0.03, self.input_potential_shape)
        elif ......
        ......

we can see that the u_xi begins as a zero matrix, and by using equation 1 we can get the v_xi matrix as a 10*10 matrix which full of 0.5. But according to the strategy, we should use a random number for v_xi. So in the next step, v_xi changed again accordingly, which makes our first calculation meaningless. My question is, do we really need to calculate the v_xi from u_xi at first? or we can just use random number directly?

Looking forward to your reply.

**Comment by DenseLance** [comment]
You can set the initial `output_potential` to random values **directly**, based on the stochastic strategies you used (i.e. A, B, C, D). In the case where you prefer not to use these preset strategies recommended by the original paper, we fall back to the output potential calculated by `output_potential_function()` as mentioned in equation 1. 

Hope this answers your question.
